-- MySQL Script generated by MySQL Workbench
-- Fri Nov 28 01:35:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `endereco` VARCHAR(250) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `status_usuario` ENUM('ativo', 'inativo') NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `publico_alvo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `id_Livro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `editora` VARCHAR(100) NOT NULL,
  `ano_publicacao` YEAR NOT NULL,
  `genero` VARCHAR(50) NOT NULL,
  `isbn` VARCHAR(20) NOT NULL,
  `quantidade_total` INT NOT NULL,
  `quantidade_disponivel` INT NOT NULL,
  `sinopse` TEXT NOT NULL,
  `data_registro` DATE NOT NULL,
  `categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_Livro`, `categoria_id_categoria`),
  INDEX `fk_Livro_categoria_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_Livro_categoria`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `cargo` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `data_admissao` DATE NOT NULL,
  `turno` ENUM('manha', 'tarde', 'noite') NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emprestimo` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_livro (FK)` INT NOT NULL,
  `data_emprestimo` DATE NOT NULL,
  `data_prevista` DATE NOT NULL,
  `data_devolucao` DATE NOT NULL,
  `status` ENUM('emprestado', 'devolvido', 'atrasado') NOT NULL,
  `observacoes` TEXT NOT NULL,
  `multa_gerada` DECIMAL(6,2) NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `Livro_id_Livro` INT NOT NULL,
  `Livro_categoria_id_categoria` INT NOT NULL,
  `funcionario_id_funcionario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_emprestimo`, `usuario_id_usuario`, `Livro_id_Livro`, `Livro_categoria_id_categoria`, `funcionario_id_funcionario`),
  INDEX `fk_emprestimo_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_emprestimo_Livro1_idx` (`Livro_id_Livro` ASC, `Livro_categoria_id_categoria` ASC) VISIBLE,
  INDEX `fk_emprestimo_funcionario1_idx` (`funcionario_id_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_Livro1`
    FOREIGN KEY (`Livro_id_Livro` , `Livro_categoria_id_categoria`)
    REFERENCES `mydb`.`Livro` (`id_Livro` , `categoria_id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_livro` INT NOT NULL,
  `data_reserva` DATE NOT NULL,
  `status_reserva` ENUM('ativa', 'atendida', 'cancelada') NOT NULL,
  `data_validade` DATE NOT NULL,
  `prioridade` ENUM('normal', 'alta') NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `Livro_id_Livro` INT NOT NULL,
  `Livro_categoria_id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `usuario_id_usuario`, `Livro_id_Livro`, `Livro_categoria_id_categoria`),
  INDEX `fk_reserva_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_reserva_Livro1_idx` (`Livro_id_Livro` ASC, `Livro_categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_Livro1`
    FOREIGN KEY (`Livro_id_Livro` , `Livro_categoria_id_categoria`)
    REFERENCES `mydb`.`Livro` (`id_Livro` , `categoria_id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
